-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DEMOWMS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DEMOWMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DEMOWMS` DEFAULT CHARACTER SET utf8 ;
USE `DEMOWMS` ;

-- -----------------------------------------------------
-- Table `DEMOWMS`.`LOGISTIKZENTRUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LOGISTIKZENTRUM` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_NAME` VARCHAR(100) NULL,
  `P_BESCHREIBUNG` VARCHAR(100) NULL,
  `P_BREITE` FLOAT NULL,
  `P_HOEHE` FLOAT NULL,
  `P_LAENGE` FLOAT NULL,
  PRIMARY KEY (`P_OID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`LHMTYPZUORDUNG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LHMTYPZUORDUNG` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `LAGERHILFSMITTELTYP_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_LHMTYPZUORDUNG_LAGERHILFSMITTELTYP1_idx` (`LAGERHILFSMITTELTYP_P_OID` ASC),
  CONSTRAINT `fk_LHMTYPZUORDUNG_LAGERHILFSMITTELTYP1`
    FOREIGN KEY (`LAGERHILFSMITTELTYP_P_OID`)
    REFERENCES `DEMOWMS`.`LAGERHILFSMITTELTYP` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`LAGERHILFSMITTELTYP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LAGERHILFSMITTELTYP` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_EIGEN_GEWICHT` FLOAT NULL,
  `P_OV_TRAGLAST` FLOAT NULL,
  `P_POS_BREITE` FLOAT NULL,
  `P_POS_TIEFE` FLOAT NULL,
  `P_TRAG_LAST` FLOAT NULL,
  `P_HOEHE` FLOAT NULL,
  `P_GEWICHTS_EINHEIT` VARCHAR(45) NULL,
  `P_BEZEICHNUNG` VARCHAR(100) NULL,
  `LHMTYPZUORDUNG_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_LAGERHILFSMITTELTYP_LHMTYPZUORDUNG1_idx` (`LHMTYPZUORDUNG_P_OID` ASC),
  CONSTRAINT `fk_LAGERHILFSMITTELTYP_LHMTYPZUORDUNG1`
    FOREIGN KEY (`LHMTYPZUORDUNG_P_OID`)
    REFERENCES `DEMOWMS`.`LHMTYPZUORDUNG` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`ARTIKELLHMTYP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`ARTIKELLHMTYP` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_HOEHE` FLOAT NULL,
  `P_MENGE` INT NULL,
  `P_STAPEL_ANZAHL` INT NULL,
  `P_EINHEIT_HOHE` VARCHAR(45) NULL,
  `LAGERHILFSMITTELTYP_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_ARTIKELLHMTYP_LAGERHILFSMITTELTYP1_idx` (`LAGERHILFSMITTELTYP_P_OID` ASC),
  CONSTRAINT `fk_ARTIKELLHMTYP_LAGERHILFSMITTELTYP1`
    FOREIGN KEY (`LAGERHILFSMITTELTYP_P_OID`)
    REFERENCES `DEMOWMS`.`LAGERHILFSMITTELTYP` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`LAGERBEREICH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LAGERBEREICH` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_SGLN_ID` INT NULL,
  `P_BARCODE_LAGERBEREICH` INT NULL,
  `P_BESCHREIBUNG` VARCHAR(100) NULL,
  `P_HOEHE` FLOAT NULL,
  `P_EINHEIT_HOEHE` VARCHAR(45) NULL,
  `LOGISTIKZENTRUM_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_LAGERBEREICH_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
  CONSTRAINT `fk_LAGERBEREICH_LOGISTIKZENTRUM1`
    FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
    REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`LOADING_AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LOADING_AREA` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_SGLN_ID` INT NULL,
  `P_BREITE` FLOAT NULL,
  `P_LAENGE` FLOAT NULL,
  `LAGERBEREICH_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_LOADING_AREA_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID` ASC),
  CONSTRAINT `fk_LOADING_AREA_LAGERBEREICH1`
    FOREIGN KEY (`LAGERBEREICH_P_OID`)
    REFERENCES `DEMOWMS`.`LAGERBEREICH` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`STELLPLATZ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`STELLPLATZ` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_SGLN_ID` INT NULL,
  `P_POS_BREITE` FLOAT NULL,
  `P_POSITION` FLOAT NULL,
  `P_POS_TIEFE` FLOAT NULL,
  `P_OBERGRENZE` FLOAT NULL,
  `LAGERBEREICH_P_OID` INT NULL,
  `LOADING_AREA_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_Stellplatz_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID` ASC),
  INDEX `fk_Stellplatz_LOADING_AREA1_idx` (`LOADING_AREA_P_OID` ASC),
  CONSTRAINT `fk_Stellplatz_LAGERBEREICH1`
    FOREIGN KEY (`LAGERBEREICH_P_OID`)
    REFERENCES `DEMOWMS`.`LAGERBEREICH` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stellplatz_LOADING_AREA1`
    FOREIGN KEY (`LOADING_AREA_P_OID`)
    REFERENCES `DEMOWMS`.`LOADING_AREA` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`FAHRZEUGTYP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`FAHRZEUGTYP` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_BESCHREIBUNG` VARCHAR(100) NULL,
  `P_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`P_OID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`FAHRZEUG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`FAHRZEUG` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_FAHRZEUG_ID` INT NULL,
  `P_IP_ADRESSE` INT NULL,
  `P_MUSS_TLHM_AUFNEHMEN` TINYINT NULL,
  `P_BETRIEBSTUNDEN` INT NULL,
  `LOGISTIKZENTRUM_P_OID` INT NULL,
  `FAHRZEUGTYP_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_FAHRZEUG_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
  INDEX `fk_FAHRZEUG_FAHRZEUGTYP1_idx` (`FAHRZEUGTYP_P_OID` ASC),
  CONSTRAINT `fk_FAHRZEUG_LOGISTIKZENTRUM1`
    FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
    REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAHRZEUG_FAHRZEUGTYP1`
    FOREIGN KEY (`FAHRZEUGTYP_P_OID`)
    REFERENCES `DEMOWMS`.`FAHRZEUGTYP` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`TRANSPORTAUFTRAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`TRANSPORTAUFTRAG` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_TRANSPORTNUMMER` INT NULL,
  `P_QUELLE` VARCHAR(100) NULL,
  `P_ZIEL` VARCHAR(100) NULL,
  `FAHRZEUG_P_OID` INT NULL,
  `LOGISTIKZENTRUM_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_TRANSPORTAUFTRAG_FAHRZEUG1_idx` (`FAHRZEUG_P_OID` ASC),
  INDEX `fk_TRANSPORTAUFTRAG_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
  CONSTRAINT `fk_TRANSPORTAUFTRAG_FAHRZEUG1`
    FOREIGN KEY (`FAHRZEUG_P_OID`)
    REFERENCES `DEMOWMS`.`FAHRZEUG` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSPORTAUFTRAG_LOGISTIKZENTRUM1`
    FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
    REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`TRANSPORTHILFSMITTEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`TRANSPORTHILFSMITTEL` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_NAME` VARCHAR(100) NULL,
  `P_GRAI_ID` INT NULL,
  `P_LANGE` FLOAT NULL,
  `P_BREITE` FLOAT NULL,
  `FAHRZEUG_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_Transporthilfsmittel_FAHRZEUG1_idx` (`FAHRZEUG_P_OID` ASC),
  CONSTRAINT `fk_Transporthilfsmittel_FAHRZEUG1`
    FOREIGN KEY (`FAHRZEUG_P_OID`)
    REFERENCES `DEMOWMS`.`FAHRZEUG` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`LAGERHILFSMITTEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LAGERHILFSMITTEL` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_GRAI_ID` INT NULL,
  `TRANSPORTAUFTRAG_P_OID` INT NULL,
  `STELLPLATZ_P_OID` INT NULL,
  `TRANSPORTHILFSMITTEL_P_OID` INT NULL,
  `LAGERHILFSMITTELTYP_P_OID` INT NULL,
  `LAGERHILFSMITTEL_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_LAGERHILFSMITTEL_TRANSPORTAUFTRAG1_idx` (`TRANSPORTAUFTRAG_P_OID` ASC),
  INDEX `fk_LAGERHILFSMITTEL_Stellplatz1_idx` (`STELLPLATZ_P_OID` ASC),
  INDEX `fk_LAGERHILFSMITTEL_Transporthilfsmittel1_idx` (`TRANSPORTHILFSMITTEL_P_OID` ASC),
  INDEX `fk_LAGERHILFSMITTEL_LAGERHILFSMITTELTYP1_idx` (`LAGERHILFSMITTELTYP_P_OID` ASC),
  INDEX `fk_LAGERHILFSMITTEL_LAGERHILFSMITTEL1_idx` (`LAGERHILFSMITTEL_P_OID` ASC),
  CONSTRAINT `fk_LAGERHILFSMITTEL_TRANSPORTAUFTRAG1`
    FOREIGN KEY (`TRANSPORTAUFTRAG_P_OID`)
    REFERENCES `DEMOWMS`.`TRANSPORTAUFTRAG` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LAGERHILFSMITTEL_Stellplatz1`
    FOREIGN KEY (`STELLPLATZ_P_OID`)
    REFERENCES `DEMOWMS`.`STELLPLATZ` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LAGERHILFSMITTEL_Transporthilfsmittel1`
    FOREIGN KEY (`TRANSPORTHILFSMITTEL_P_OID`)
    REFERENCES `DEMOWMS`.`TRANSPORTHILFSMITTEL` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LAGERHILFSMITTEL_LAGERHILFSMITTELTYP1`
    FOREIGN KEY (`LAGERHILFSMITTELTYP_P_OID`)
    REFERENCES `DEMOWMS`.`LAGERHILFSMITTELTYP` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LAGERHILFSMITTEL_LAGERHILFSMITTEL1`
    FOREIGN KEY (`LAGERHILFSMITTEL_P_OID`)
    REFERENCES `DEMOWMS`.`LAGERHILFSMITTEL` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`BESTELLUNG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`BESTELLUNG` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_ANLIEFERTAG` DATE NULL,
  `P_BESTELLNUMMER` INT NULL,
  `P_GEPLANTES_LIEFERDATUM` DATE NULL,
  `P_TEXT` VARCHAR(1000) NULL,
  `LOGISTIKZENTRUM_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_BESTELLUNG_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
  CONSTRAINT `fk_BESTELLUNG_LOGISTIKZENTRUM1`
    FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
    REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`WARE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`WARE` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_MENGE` INT NULL,
  `P_EINHEITMENGE` VARCHAR(45) NULL,
  `P_EINHEITVOLUMEN` VARCHAR(45) NULL,
  `P_VOLUMEN` FLOAT NULL,
  `P_PACKUNGSGROESSE` FLOAT NULL,
  `LOGISTIKZENTRUM_P_OID` INT NULL,
  `LAGERHILFSMITTEL_P_OID` INT NULL,
  `BESTELLUNG_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_WARE_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
  INDEX `fk_WARE_LAGERHILFSMITTEL1_idx` (`LAGERHILFSMITTEL_P_OID` ASC),
  INDEX `fk_WARE_BESTELLUNG1_idx` (`BESTELLUNG_P_OID` ASC),
  CONSTRAINT `fk_WARE_LOGISTIKZENTRUM1`
    FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
    REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WARE_LAGERHILFSMITTEL1`
    FOREIGN KEY (`LAGERHILFSMITTEL_P_OID`)
    REFERENCES `DEMOWMS`.`LAGERHILFSMITTEL` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WARE_BESTELLUNG1`
    FOREIGN KEY (`BESTELLUNG_P_OID`)
    REFERENCES `DEMOWMS`.`BESTELLUNG` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMOWMS`.`ARTIKEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMOWMS`.`ARTIKEL` (
  `P_OID` INT NOT NULL AUTO_INCREMENT,
  `P_ZEITSTEMPEL` DATE NULL,
  `P_ANLAGE_DATUM` DATE NULL,
  `P_LETZTE_AENDERUNG` DATE NULL,
  `P_SGTIN_ID` INT NULL,
  `P_ADDITIONAL_TEXT` VARCHAR(100) NULL,
  `P_BESCHREIBUNG` VARCHAR(100) NULL,
  `P_BREITE` FLOAT NULL,
  `P_GESAMTMENGE` INT NULL,
  `P_HOEHE` FLOAT NULL,
  `P_LAENGE` FLOAT NULL,
  `P_MAX_TEMPERATUR` FLOAT NULL,
  `P_MIN_TEMPERATUR` FLOAT NULL,
  `P_STUECKGEWICHT` FLOAT NULL,
  `P_STUECKVOLUMEN` FLOAT NULL,
  `WARE_P_OID` INT NULL,
  `ARTIKELLHMTYP_P_OID` INT NULL,
  PRIMARY KEY (`P_OID`),
  INDEX `fk_ARTIKEL_WARE1_idx` (`WARE_P_OID` ASC),
  INDEX `fk_ARTIKEL_ARTIKELLHMTYP1_idx` (`ARTIKELLHMTYP_P_OID` ASC),
  CONSTRAINT `fk_ARTIKEL_WARE1`
    FOREIGN KEY (`WARE_P_OID`)
    REFERENCES `DEMOWMS`.`WARE` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTIKEL_ARTIKELLHMTYP1`
    FOREIGN KEY (`ARTIKELLHMTYP_P_OID`)
    REFERENCES `DEMOWMS`.`ARTIKELLHMTYP` (`P_OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
