<?php

//from db_setup_tables_v4.sql

class db_setup{

  public $db_setup_string = "

  -- MySQL Workbench Forward Engineering

  SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
  SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
  SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

  -- -----------------------------------------------------
  -- Schema DEMOWMS
  -- -----------------------------------------------------

  -- -----------------------------------------------------
  -- Schema DEMOWMS
  -- -----------------------------------------------------
  CREATE SCHEMA IF NOT EXISTS `DEMOWMS` DEFAULT CHARACTER SET utf8 ;
  USE `DEMOWMS` ;

  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`LOGISTIKZENTRUM`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LOGISTIKZENTRUM` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_NAME` VARCHAR(100) NULL,
    `P_BESCHREIBUNG` VARCHAR(100) NULL,
    `P_BREITE` FLOAT NULL,
    `P_HOEHE` FLOAT NULL,
    `P_LAENGE` FLOAT NULL,
    PRIMARY KEY (`P_OID`))
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`LAGERBEREICH`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LAGERBEREICH` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_SGLN_ID` INT NULL,
    `P_BARCODE_LAGERBEREICH` INT NULL,
    `P_BESCHREIBUNG` VARCHAR(100) NULL,
    `P_HOEHE` FLOAT NULL,
    `P_EINHEIT_HOEHE` VARCHAR(45) NULL,
    `LOGISTIKZENTRUM_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_LAGERBEREICH_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
    CONSTRAINT `fk_LAGERBEREICH_LOGISTIKZENTRUM1`
      FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
      REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`LOADING_AREA`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LOADING_AREA` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_SGLN_ID` INT NULL,
    `P_BREITE` FLOAT NULL,
    `P_LAENGE` FLOAT NULL,
    `LAGERBEREICH_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_LOADING_AREA_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID` ASC),
    CONSTRAINT `fk_LOADING_AREA_LAGERBEREICH1`
      FOREIGN KEY (`LAGERBEREICH_P_OID`)
      REFERENCES `DEMOWMS`.`LAGERBEREICH` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`STELLPLATZ`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`STELLPLATZ` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_SGLN_ID` INT NULL,
    `P_STATUS` VARCHAR(45) NULL,
    `P_POS_BREITE` FLOAT NULL,
    `P_POSITION` FLOAT NULL,
    `P_POS_TIEFE` FLOAT NULL,
    `P_OBERGRENZE` FLOAT NULL,
    `LAGERBEREICH_P_OID` INT NULL,
    `LOADING_AREA_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_Stellplatz_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID` ASC),
    INDEX `fk_Stellplatz_LOADING_AREA1_idx` (`LOADING_AREA_P_OID` ASC),
    CONSTRAINT `fk_Stellplatz_LAGERBEREICH1`
      FOREIGN KEY (`LAGERBEREICH_P_OID`)
      REFERENCES `DEMOWMS`.`LAGERBEREICH` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_Stellplatz_LOADING_AREA1`
      FOREIGN KEY (`LOADING_AREA_P_OID`)
      REFERENCES `DEMOWMS`.`LOADING_AREA` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`FAHRZEUGTYP`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`FAHRZEUGTYP` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_BESCHREIBUNG` VARCHAR(100) NULL,
    `P_NAME` VARCHAR(100) NULL,
    PRIMARY KEY (`P_OID`))
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`STETIG_FOERDERER`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`STETIG_FOERDERER` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_LAENGE` FLOAT NULL,
    `LAGERBEREICH_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_STETIG_FOERDERER_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID` ASC),
    CONSTRAINT `fk_STETIG_FOERDERER_LAGERBEREICH1`
      FOREIGN KEY (`LAGERBEREICH_P_OID`)
      REFERENCES `DEMOWMS`.`LAGERBEREICH` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`FLURFOERDERMITTEL`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`FLURFOERDERMITTEL` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_GIAI_ID` INT NULL COMMENT '\n',
    `P_IP_ADRESSE` INT NULL,
    `P_MUSS_TLHM_AUFNEHMEN` TINYINT NULL,
    `P_BETRIEBSTUNDEN` INT NULL,
    `LOGISTIKZENTRUM_P_OID` INT NULL,
    `FAHRZEUGTYP_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_FLURFOERDERMITTEL_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
    INDEX `fk_FLURFOERDERMITTEL_FAHRZEUGTYP1_idx` (`FAHRZEUGTYP_P_OID` ASC),
    CONSTRAINT `fk_FLURFOERDERMITTEL_LOGISTIKZENTRUM1`
      FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
      REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_FLURFOERDERMITTEL_FAHRZEUGTYP1`
      FOREIGN KEY (`FAHRZEUGTYP_P_OID`)
      REFERENCES `DEMOWMS`.`FAHRZEUGTYP` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`ANHAENGER`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`ANHAENGER` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_NAME` VARCHAR(100) NULL,
    `P_GRAI_ID` INT NULL,
    `P_LANGE` FLOAT NULL,
    `P_BREITE` FLOAT NULL,
    `FLURFOERDERMITTEL_P_OID` INT NULL,
    `STELLPLATZ_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_ANHAENGER_FLURFOERDERMITTEL1_idx` (`FLURFOERDERMITTEL_P_OID` ASC),
    INDEX `fk_ANHAENGER_STELLPLATZ1_idx` (`STELLPLATZ_P_OID` ASC),
    CONSTRAINT `fk_ANHAENGER_FLURFOERDERMITTEL1`
      FOREIGN KEY (`FLURFOERDERMITTEL_P_OID`)
      REFERENCES `DEMOWMS`.`FLURFOERDERMITTEL` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_ANHAENGER_STELLPLATZ1`
      FOREIGN KEY (`STELLPLATZ_P_OID`)
      REFERENCES `DEMOWMS`.`STELLPLATZ` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`TRANSPORTAUFTRAG`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`TRANSPORTAUFTRAG` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_TRANSPORTNUMMER` INT NULL,
    `P_QUELLE` VARCHAR(45) NULL,
    `P_ZIEL` VARCHAR(45) NULL,
    `P_STATUS` VARCHAR(45) NULL,
    `LOGISTIKZENTRUM_P_OID` INT NULL,
    `FLURFOERDERMITTEL_P_OID` INT NULL,
    `STETIG_FOERDERER_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_TRANSPORTAUFTRAG_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
    INDEX `fk_TRANSPORTAUFTRAG_FLURFOERDERMITTEL1_idx` (`FLURFOERDERMITTEL_P_OID` ASC),
    INDEX `fk_TRANSPORTAUFTRAG_STETIG_FOERDERER1_idx` (`STETIG_FOERDERER_P_OID` ASC),
    CONSTRAINT `fk_TRANSPORTAUFTRAG_LOGISTIKZENTRUM1`
      FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
      REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_TRANSPORTAUFTRAG_FLURFOERDERMITTEL1`
      FOREIGN KEY (`FLURFOERDERMITTEL_P_OID`)
      REFERENCES `DEMOWMS`.`FLURFOERDERMITTEL` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_TRANSPORTAUFTRAG_STETIG_FOERDERER1`
      FOREIGN KEY (`STETIG_FOERDERER_P_OID`)
      REFERENCES `DEMOWMS`.`STETIG_FOERDERER` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`LADEHILFSMITTELTYP`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LADEHILFSMITTELTYP` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_EIGEN_GEWICHT` FLOAT NULL,
    `P_OV_TRAGLAST` FLOAT NULL,
    `P_POS_BREITE` FLOAT NULL,
    `P_POS_TIEFE` FLOAT NULL,
    `P_TRAG_LAST` FLOAT NULL,
    `P_HOEHE` FLOAT NULL,
    `P_GEWICHTS_EINHEIT` VARCHAR(45) NULL,
    `P_BEZEICHNUNG` VARCHAR(100) NULL,
    `LHMTYPZUORDUNG_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`))
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`LADEHILFSMITTEL`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`LADEHILFSMITTEL` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_GRAI_ID` INT NULL,
    `STETIG_FOERDERER_P_OID` INT NULL,
    `ANHAENGER_P_OID` INT NULL,
    `FLURFOERDERMITTEL_P_OID` INT NULL,
    `TRANSPORTAUFTRAG_P_OID` INT NULL,
    `STELLPLATZ_P_OID` INT NULL,
    `LADEHILFSMITTEL_P_OID` INT NULL,
    `LADEHILFSMITTELTYP_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_LADEHILFSMITTEL_STETIG_FOERDERER1_idx` (`STETIG_FOERDERER_P_OID` ASC),
    INDEX `fk_LADEHILFSMITTEL_ANHAENGER1_idx` (`ANHAENGER_P_OID` ASC),
    INDEX `fk_LADEHILFSMITTEL_FLURFOERDERMITTEL1_idx` (`FLURFOERDERMITTEL_P_OID` ASC),
    INDEX `fk_LADEHILFSMITTEL_TRANSPORTAUFTRAG1_idx` (`TRANSPORTAUFTRAG_P_OID` ASC),
    INDEX `fk_LADEHILFSMITTEL_STELLPLATZ1_idx` (`STELLPLATZ_P_OID` ASC),
    INDEX `fk_LADEHILFSMITTEL_LADEHILFSMITTEL1_idx` (`LADEHILFSMITTEL_P_OID` ASC),
    INDEX `fk_LADEHILFSMITTEL_LADEHILFSMITTELTYP1_idx` (`LADEHILFSMITTELTYP_P_OID` ASC),
    CONSTRAINT `fk_LADEHILFSMITTEL_STETIG_FOERDERER1`
      FOREIGN KEY (`STETIG_FOERDERER_P_OID`)
      REFERENCES `DEMOWMS`.`STETIG_FOERDERER` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_ANHAENGER1`
      FOREIGN KEY (`ANHAENGER_P_OID`)
      REFERENCES `DEMOWMS`.`ANHAENGER` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_FLURFOERDERMITTEL1`
      FOREIGN KEY (`FLURFOERDERMITTEL_P_OID`)
      REFERENCES `DEMOWMS`.`FLURFOERDERMITTEL` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_TRANSPORTAUFTRAG1`
      FOREIGN KEY (`TRANSPORTAUFTRAG_P_OID`)
      REFERENCES `DEMOWMS`.`TRANSPORTAUFTRAG` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_STELLPLATZ1`
      FOREIGN KEY (`STELLPLATZ_P_OID`)
      REFERENCES `DEMOWMS`.`STELLPLATZ` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_LADEHILFSMITTEL1`
      FOREIGN KEY (`LADEHILFSMITTEL_P_OID`)
      REFERENCES `DEMOWMS`.`LADEHILFSMITTEL` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_LADEHILFSMITTELTYP1`
      FOREIGN KEY (`LADEHILFSMITTELTYP_P_OID`)
      REFERENCES `DEMOWMS`.`LADEHILFSMITTELTYP` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`BESTELLUNG`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`BESTELLUNG` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_ANLIEFERTAG` DATE NULL,
    `P_BESTELLNUMMER` INT NULL,
    `P_GEPLANTES_LIEFERDATUM` DATE NULL,
    `P_TEXT` VARCHAR(1000) NULL,
    `LOGISTIKZENTRUM_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_BESTELLUNG_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
    CONSTRAINT `fk_BESTELLUNG_LOGISTIKZENTRUM1`
      FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
      REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`WARE`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`WARE` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_MENGE` INT NULL,
    `P_EINHEITMENGE` VARCHAR(45) NULL,
    `P_EINHEITVOLUMEN` VARCHAR(45) NULL,
    `P_VOLUMEN` FLOAT NULL,
    `P_PACKUNGSGROESSE` FLOAT NULL,
    `LOGISTIKZENTRUM_P_OID` INT NULL,
    `BESTELLUNG_P_OID` INT NULL,
    `LADEHILFSMITTEL_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_WARE_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID` ASC),
    INDEX `fk_WARE_BESTELLUNG1_idx` (`BESTELLUNG_P_OID` ASC),
    INDEX `fk_WARE_LADEHILFSMITTEL1_idx` (`LADEHILFSMITTEL_P_OID` ASC),
    CONSTRAINT `fk_WARE_LOGISTIKZENTRUM1`
      FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`)
      REFERENCES `DEMOWMS`.`LOGISTIKZENTRUM` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_WARE_BESTELLUNG1`
      FOREIGN KEY (`BESTELLUNG_P_OID`)
      REFERENCES `DEMOWMS`.`BESTELLUNG` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT `fk_WARE_LADEHILFSMITTEL1`
      FOREIGN KEY (`LADEHILFSMITTEL_P_OID`)
      REFERENCES `DEMOWMS`.`LADEHILFSMITTEL` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table `DEMOWMS`.`ARTIKEL`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `DEMOWMS`.`ARTIKEL` (
    `P_OID` INT NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` DATE NULL,
    `P_ANLAGE_DATUM` DATE NULL,
    `P_LETZTE_AENDERUNG` DATE NULL,
    `P_SGTIN_ID` INT NULL,
    `P_ADDITIONAL_TEXT` VARCHAR(100) NULL,
    `P_BESCHREIBUNG` VARCHAR(100) NULL,
    `P_BREITE` FLOAT NULL,
    `P_GESAMTMENGE` INT NULL,
    `P_HOEHE` FLOAT NULL,
    `P_LAENGE` FLOAT NULL,
    `P_MAX_TEMPERATUR` FLOAT NULL,
    `P_MIN_TEMPERATUR` FLOAT NULL,
    `P_STUECKGEWICHT` FLOAT NULL,
    `P_STUECKVOLUMEN` FLOAT NULL,
    `WARE_P_OID` INT NULL,
    `ARTIKELLHMTYP_P_OID` INT NULL,
    PRIMARY KEY (`P_OID`),
    INDEX `fk_ARTIKEL_WARE1_idx` (`WARE_P_OID` ASC),
    CONSTRAINT `fk_ARTIKEL_WARE1`
      FOREIGN KEY (`WARE_P_OID`)
      REFERENCES `DEMOWMS`.`WARE` (`P_OID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  SET SQL_MODE=@OLD_SQL_MODE;
  SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
  SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

  ";

  public $db_setup_string_Intelli = "


  SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
  SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
  SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

  -- -----------------------------------------------------
  -- Schema DEMOWMS
  -- -----------------------------------------------------

  -- -----------------------------------------------------
  -- Schema DEMOWMS
  -- -----------------------------------------------------
  CREATE SCHEMA IF NOT EXISTS `DEMOWMS` DEFAULT CHARACTER SET utf8 ;
  USE `DEMOWMS` ;




  -- MySQL dump 10.13  Distrib 5.7.9, for osx10.9 (x86_64)
  --
  -- Host: 127.0.0.1    Database: DEMOWMS
  -- ------------------------------------------------------
  -- Server version	5.6.33

  /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
  /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
  /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
  /*!40101 SET NAMES utf8 */;
  /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
  /*!40103 SET TIME_ZONE='+00:00' */;
  /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
  /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
  /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
  /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

  --
  -- Table structure for table `ANHAENGER`
  --

  DROP TABLE IF EXISTS `ANHAENGER`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `ANHAENGER` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_NAME` varchar(100) DEFAULT NULL,
    `P_GRAI_ID` int(11) DEFAULT NULL,
    `P_LANGE` float DEFAULT NULL,
    `P_BREITE` float DEFAULT NULL,
    `FLURFOERDERMITTEL_P_OID` int(11) DEFAULT NULL,
    `STELLPLATZ_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_ANHAENGER_FLURFOERDERMITTEL1_idx` (`FLURFOERDERMITTEL_P_OID`),
    KEY `fk_ANHAENGER_STELLPLATZ1_idx` (`STELLPLATZ_P_OID`),
    CONSTRAINT `fk_ANHAENGER_FLURFOERDERMITTEL1` FOREIGN KEY (`FLURFOERDERMITTEL_P_OID`) REFERENCES `FLURFOERDERMITTEL` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_ANHAENGER_STELLPLATZ1` FOREIGN KEY (`STELLPLATZ_P_OID`) REFERENCES `STELLPLATZ` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `ANHAENGER`
  --

  LOCK TABLES `ANHAENGER` WRITE;
  /*!40000 ALTER TABLE `ANHAENGER` DISABLE KEYS */;
  INSERT INTO `ANHAENGER` VALUES (1,'GLT_Anhänger',50000001,2000,900,3,21),(2,'GLT_Anhänger',50000002,2000,900,3,22);
  /*!40000 ALTER TABLE `ANHAENGER` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `ARTIKEL`
  --

  DROP TABLE IF EXISTS `ARTIKEL`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `ARTIKEL` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_SGTIN_ID` int(11) DEFAULT NULL,
    `P_ADDITIONAL_TEXT` varchar(100) DEFAULT NULL,
    `P_BESCHREIBUNG` varchar(100) DEFAULT NULL,
    `P_BREITE` float DEFAULT NULL,
    `P_GESAMTMENGE` int(11) DEFAULT NULL,
    `P_HOEHE` float DEFAULT NULL,
    `P_LAENGE` float DEFAULT NULL,
    `P_MAX_TEMPERATUR` float DEFAULT NULL,
    `P_MIN_TEMPERATUR` float DEFAULT NULL,
    `P_STUECKGEWICHT` float DEFAULT NULL,
    `P_STUECKVOLUMEN` float DEFAULT NULL,
    `WARE_P_OID` int(11) DEFAULT NULL,
    `ARTIKELLHMTYP_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_ARTIKEL_WARE1_idx` (`WARE_P_OID`),
    CONSTRAINT `fk_ARTIKEL_WARE1` FOREIGN KEY (`WARE_P_OID`) REFERENCES `WARE` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `ARTIKEL`
  --

  LOCK TABLES `ARTIKEL` WRITE;
  /*!40000 ALTER TABLE `ARTIKEL` DISABLE KEYS */;
  INSERT INTO `ARTIKEL` VALUES (1,NULL,NULL,NULL,90909001,'Karton','8 x 160mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,1,NULL),(2,NULL,NULL,NULL,90909002,'Karton','8 x 170mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,1,NULL),(3,NULL,NULL,NULL,90909003,'Karton','8 x 180mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,1,NULL),(4,NULL,NULL,NULL,90909004,'Karton','8 x 190mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,1,NULL),(5,NULL,NULL,NULL,90909005,'Karton','8 x 200mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,1,NULL),(6,NULL,NULL,NULL,90909006,'Karton','8 x 210mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,1,NULL),(7,NULL,NULL,NULL,90909011,'Karton','8 x 160mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,2,NULL),(8,NULL,NULL,NULL,90909012,'Karton','8 x 170mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,2,NULL),(9,NULL,NULL,NULL,90909013,'Karton','8 x 180mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,2,NULL),(10,NULL,NULL,NULL,90909014,'Karton','8 x 190mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,2,NULL),(11,NULL,NULL,NULL,90909015,'Karton','8 x 200mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,2,NULL),(12,NULL,NULL,NULL,90909016,'Karton','8 x 210mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,2,NULL),(13,NULL,NULL,NULL,90909021,'Karton','8 x 160mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,3,NULL),(14,NULL,NULL,NULL,90909022,'Karton','8 x 170mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,3,NULL),(15,NULL,NULL,NULL,90909023,'Karton','8 x 180mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,3,NULL),(16,NULL,NULL,NULL,90909024,'Karton','8 x 190mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,3,NULL),(17,NULL,NULL,NULL,90909025,'Karton','8 x 200mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,3,NULL),(18,NULL,NULL,NULL,90909026,'Karton','8 x 210mm Konstruktionsschrauben TX Senkkopf ',50,200,60,150,100,-50,0.0001,0.001,3,NULL);
  /*!40000 ALTER TABLE `ARTIKEL` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `BESTELLUNG`
  --

  DROP TABLE IF EXISTS `BESTELLUNG`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `BESTELLUNG` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_ANLIEFERTAG` date DEFAULT NULL,
    `P_BESTELLNUMMER` int(11) DEFAULT NULL,
    `P_GEPLANTES_LIEFERDATUM` date DEFAULT NULL,
    `P_TEXT` varchar(1000) DEFAULT NULL,
    `LOGISTIKZENTRUM_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_BESTELLUNG_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID`),
    CONSTRAINT `fk_BESTELLUNG_LOGISTIKZENTRUM1` FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`) REFERENCES `LOGISTIKZENTRUM` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `BESTELLUNG`
  --

  LOCK TABLES `BESTELLUNG` WRITE;
  /*!40000 ALTER TABLE `BESTELLUNG` DISABLE KEYS */;
  INSERT INTO `BESTELLUNG` VALUES (1,NULL,NULL,NULL,'2019-06-14',33301,'2019-06-14','Bestellung 01',1),(2,NULL,NULL,NULL,'2019-06-15',33302,'2019-06-14','Bestellung 02',1),(3,NULL,NULL,NULL,'2019-06-16',33303,'2019-06-14','Bestellung 03',1),(4,NULL,NULL,NULL,'2019-06-17',33304,'2019-06-14','Bestellung 04',1),(5,NULL,NULL,NULL,'2019-06-18',33305,'2019-06-14','Bestellung 05',1),(6,NULL,NULL,NULL,'2019-06-19',33306,'2019-06-14','Bestellung 06',1),(7,NULL,NULL,NULL,'2019-06-20',33307,'2019-06-14','Bestellung 07',1),(8,NULL,NULL,NULL,'2019-06-21',33308,'2019-06-14','Bestellung 08',1),(9,NULL,NULL,NULL,'2019-06-22',33309,'2019-06-14','Bestellung 09',1),(10,NULL,NULL,NULL,'2019-06-23',33300,'2019-06-14','Bestellung 00',1);
  /*!40000 ALTER TABLE `BESTELLUNG` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `FAHRZEUGTYP`
  --

  DROP TABLE IF EXISTS `FAHRZEUGTYP`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `FAHRZEUGTYP` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_BESCHREIBUNG` varchar(100) DEFAULT NULL,
    `P_NAME` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`P_OID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `FAHRZEUGTYP`
  --

  LOCK TABLES `FAHRZEUGTYP` WRITE;
  /*!40000 ALTER TABLE `FAHRZEUGTYP` DISABLE KEYS */;
  INSERT INTO `FAHRZEUGTYP` VALUES (1,NULL,NULL,NULL,'Vierradstapler 1.6 - 2.0t; Elektro-Gabelstapler','EFG 320'),(2,NULL,NULL,NULL,'Standschlepper 5.0t; Elektro-Schlepper','EZS 350'),(3,'2018-05-17','2018-05-17','2018-05-17','Ameise',NULL);
  /*!40000 ALTER TABLE `FAHRZEUGTYP` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `FLURFOERDERMITTEL`
  --

  DROP TABLE IF EXISTS `FLURFOERDERMITTEL`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `FLURFOERDERMITTEL` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_GIAI_ID` int(11) DEFAULT NULL COMMENT '\n',
    `P_IP_ADRESSE` int(11) DEFAULT NULL,
    `P_MUSS_TLHM_AUFNEHMEN` tinyint(4) DEFAULT NULL,
    `P_BETRIEBSTUNDEN` int(11) DEFAULT NULL,
    `LOGISTIKZENTRUM_P_OID` int(11) DEFAULT NULL,
    `FAHRZEUGTYP_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_FLURFOERDERMITTEL_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID`),
    KEY `fk_FLURFOERDERMITTEL_FAHRZEUGTYP1_idx` (`FAHRZEUGTYP_P_OID`),
    CONSTRAINT `fk_FLURFOERDERMITTEL_FAHRZEUGTYP1` FOREIGN KEY (`FAHRZEUGTYP_P_OID`) REFERENCES `FAHRZEUGTYP` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_FLURFOERDERMITTEL_LOGISTIKZENTRUM1` FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`) REFERENCES `LOGISTIKZENTRUM` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `FLURFOERDERMITTEL`
  --

  LOCK TABLES `FLURFOERDERMITTEL` WRITE;
  /*!40000 ALTER TABLE `FLURFOERDERMITTEL` DISABLE KEYS */;
  INSERT INTO `FLURFOERDERMITTEL` VALUES (1,NULL,NULL,NULL,2501,1921680100,0,80000,1,1),(2,NULL,NULL,NULL,2502,1921680101,0,70000,1,1),(3,'2018-05-17',NULL,'2018-05-17',60000001,1921680103,1,40000,1,2),(4,'2018-05-17',NULL,'2018-05-17',60000002,1921680104,1,100,1,3);
  /*!40000 ALTER TABLE `FLURFOERDERMITTEL` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `LADEHILFSMITTEL`
  --

  DROP TABLE IF EXISTS `LADEHILFSMITTEL`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `LADEHILFSMITTEL` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_GRAI_ID` int(11) DEFAULT NULL,
    `STETIG_FOERDERER_P_OID` int(11) DEFAULT NULL,
    `ANHAENGER_P_OID` int(11) DEFAULT NULL,
    `FLURFOERDERMITTEL_P_OID` int(11) DEFAULT NULL,
    `TRANSPORTAUFTRAG_P_OID` int(11) DEFAULT NULL,
    `STELLPLATZ_P_OID` int(11) DEFAULT NULL,
    `LADEHILFSMITTEL_P_OID` int(11) DEFAULT NULL,
    `LADEHILFSMITTELTYP_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_LADEHILFSMITTEL_STETIG_FOERDERER1_idx` (`STETIG_FOERDERER_P_OID`),
    KEY `fk_LADEHILFSMITTEL_ANHAENGER1_idx` (`ANHAENGER_P_OID`),
    KEY `fk_LADEHILFSMITTEL_FLURFOERDERMITTEL1_idx` (`FLURFOERDERMITTEL_P_OID`),
    KEY `fk_LADEHILFSMITTEL_TRANSPORTAUFTRAG1_idx` (`TRANSPORTAUFTRAG_P_OID`),
    KEY `fk_LADEHILFSMITTEL_STELLPLATZ1_idx` (`STELLPLATZ_P_OID`),
    KEY `fk_LADEHILFSMITTEL_LADEHILFSMITTEL1_idx` (`LADEHILFSMITTEL_P_OID`),
    KEY `fk_LADEHILFSMITTEL_LADEHILFSMITTELTYP1_idx` (`LADEHILFSMITTELTYP_P_OID`),
    CONSTRAINT `fk_LADEHILFSMITTEL_ANHAENGER1` FOREIGN KEY (`ANHAENGER_P_OID`) REFERENCES `ANHAENGER` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_FLURFOERDERMITTEL1` FOREIGN KEY (`FLURFOERDERMITTEL_P_OID`) REFERENCES `FLURFOERDERMITTEL` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_LADEHILFSMITTEL1` FOREIGN KEY (`LADEHILFSMITTEL_P_OID`) REFERENCES `LADEHILFSMITTEL` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_LADEHILFSMITTELTYP1` FOREIGN KEY (`LADEHILFSMITTELTYP_P_OID`) REFERENCES `LADEHILFSMITTELTYP` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_STELLPLATZ1` FOREIGN KEY (`STELLPLATZ_P_OID`) REFERENCES `STELLPLATZ` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_STETIG_FOERDERER1` FOREIGN KEY (`STETIG_FOERDERER_P_OID`) REFERENCES `STETIG_FOERDERER` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_LADEHILFSMITTEL_TRANSPORTAUFTRAG1` FOREIGN KEY (`TRANSPORTAUFTRAG_P_OID`) REFERENCES `TRANSPORTAUFTRAG` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `LADEHILFSMITTEL`
  --

  LOCK TABLES `LADEHILFSMITTEL` WRITE;
  /*!40000 ALTER TABLE `LADEHILFSMITTEL` DISABLE KEYS */;
  INSERT INTO `LADEHILFSMITTEL` VALUES (1,'2018-05-17',NULL,'2018-05-17',10000001,NULL,NULL,NULL,1,23,NULL,1),(2,'2018-05-17',NULL,'2018-05-17',10000002,NULL,NULL,NULL,2,24,NULL,1),(3,'2018-05-17',NULL,'2018-05-17',20000001,NULL,NULL,NULL,NULL,25,NULL,1),(4,'2018-05-17',NULL,'2018-05-17',10000004,NULL,NULL,NULL,NULL,NULL,NULL,1),(5,'2018-05-17',NULL,'2018-05-17',10000005,NULL,NULL,NULL,NULL,NULL,NULL,1);
  UNLOCK TABLES;

  --
  -- Table structure for table `LADEHILFSMITTELTYP`
  --

  DROP TABLE IF EXISTS `LADEHILFSMITTELTYP`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `LADEHILFSMITTELTYP` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_EIGEN_GEWICHT` float DEFAULT NULL,
    `P_OV_TRAGLAST` float DEFAULT NULL,
    `P_POS_BREITE` float DEFAULT NULL,
    `P_POS_TIEFE` float DEFAULT NULL,
    `P_TRAG_LAST` float DEFAULT NULL,
    `P_HOEHE` float DEFAULT NULL,
    `P_GEWICHTS_EINHEIT` varchar(45) DEFAULT NULL,
    `P_BEZEICHNUNG` varchar(100) DEFAULT NULL,
    `LHMTYPZUORDUNG_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `LADEHILFSMITTELTYP`
  --

  LOCK TABLES `LADEHILFSMITTELTYP` WRITE;
  /*!40000 ALTER TABLE `LADEHILFSMITTELTYP` DISABLE KEYS */;
  INSERT INTO `LADEHILFSMITTELTYP` VALUES (1,NULL,NULL,NULL,24,2000,800,1200,1000,144,'kg','largeLoadCarrier',NULL),(2,NULL,NULL,NULL,10,20,400,600,20,280,'kg','smallLoadCarrier',NULL);
  /*!40000 ALTER TABLE `LADEHILFSMITTELTYP` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `LAGERBEREICH`
  --

  DROP TABLE IF EXISTS `LAGERBEREICH`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `LAGERBEREICH` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_SGLN_ID` int(11) DEFAULT NULL,
    `P_BARCODE_LAGERBEREICH` int(11) DEFAULT NULL,
    `P_BESCHREIBUNG` varchar(100) DEFAULT NULL,
    `P_HOEHE` float DEFAULT NULL,
    `P_EINHEIT_HOEHE` varchar(45) DEFAULT NULL,
    `LOGISTIKZENTRUM_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_LAGERBEREICH_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID`),
    CONSTRAINT `fk_LAGERBEREICH_LOGISTIKZENTRUM1` FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`) REFERENCES `LOGISTIKZENTRUM` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `LAGERBEREICH`
  --

  LOCK TABLES `LAGERBEREICH` WRITE;
  /*!40000 ALTER TABLE `LAGERBEREICH` DISABLE KEYS */;
  INSERT INTO `LAGERBEREICH` VALUES (1,NULL,NULL,NULL,1234567890,888888888,'Hochregallager',8.5,'m',1),(2,NULL,NULL,NULL,987654321,777777777,'Blocklager',6.8,'m',1);
  /*!40000 ALTER TABLE `LAGERBEREICH` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `LOADING_AREA`
  --

  DROP TABLE IF EXISTS `LOADING_AREA`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `LOADING_AREA` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_SGLN_ID` int(11) DEFAULT NULL,
    `P_BREITE` float DEFAULT NULL,
    `P_LAENGE` float DEFAULT NULL,
    `LAGERBEREICH_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_LOADING_AREA_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID`),
    CONSTRAINT `fk_LOADING_AREA_LAGERBEREICH1` FOREIGN KEY (`LAGERBEREICH_P_OID`) REFERENCES `LAGERBEREICH` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `LOADING_AREA`
  --

  LOCK TABLES `LOADING_AREA` WRITE;
  /*!40000 ALTER TABLE `LOADING_AREA` DISABLE KEYS */;
  INSERT INTO `LOADING_AREA` VALUES (1,NULL,NULL,NULL,6666660,5.5,3.7,1),(2,NULL,NULL,NULL,6666661,5.5,3.7,2);
  /*!40000 ALTER TABLE `LOADING_AREA` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `LOGISTIKZENTRUM`
  --

  DROP TABLE IF EXISTS `LOGISTIKZENTRUM`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `LOGISTIKZENTRUM` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_NAME` varchar(100) DEFAULT NULL,
    `P_BESCHREIBUNG` varchar(100) DEFAULT NULL,
    `P_BREITE` float DEFAULT NULL,
    `P_HOEHE` float DEFAULT NULL,
    `P_LAENGE` float DEFAULT NULL,
    PRIMARY KEY (`P_OID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `LOGISTIKZENTRUM`
  --

  LOCK TABLES `LOGISTIKZENTRUM` WRITE;
  /*!40000 ALTER TABLE `LOGISTIKZENTRUM` DISABLE KEYS */;
  INSERT INTO `LOGISTIKZENTRUM` VALUES (1,'2018-05-14','2018-05-14','2018-05-14','fml-Versuchshalle','Hier werden experimente Durchgeführt',100,7,50);
  /*!40000 ALTER TABLE `LOGISTIKZENTRUM` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `STELLPLATZ`
  --

  DROP TABLE IF EXISTS `STELLPLATZ`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `STELLPLATZ` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_SGLN_ID` int(11) DEFAULT NULL,
    `P_STATUS` varchar(45) DEFAULT NULL,
    `P_POS_BREITE` float DEFAULT NULL,
    `P_POSITION` float DEFAULT NULL,
    `P_POS_TIEFE` float DEFAULT NULL,
    `P_OBERGRENZE` float DEFAULT NULL,
    `LAGERBEREICH_P_OID` int(11) DEFAULT NULL,
    `LOADING_AREA_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_Stellplatz_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID`),
    KEY `fk_Stellplatz_LOADING_AREA1_idx` (`LOADING_AREA_P_OID`),
    CONSTRAINT `fk_Stellplatz_LAGERBEREICH1` FOREIGN KEY (`LAGERBEREICH_P_OID`) REFERENCES `LAGERBEREICH` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Stellplatz_LOADING_AREA1` FOREIGN KEY (`LOADING_AREA_P_OID`) REFERENCES `LOADING_AREA` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `STELLPLATZ`
  --

  LOCK TABLES `STELLPLATZ` WRITE;
  /*!40000 ALTER TABLE `STELLPLATZ` DISABLE KEYS */;
  INSERT INTO `STELLPLATZ` VALUES (21,'2018-05-17',NULL,'2018-05-17',80000001,NULL,1000,1,2000,2,1,1),(22,'2018-05-17',NULL,'2018-05-17',80000002,NULL,1000,2,2000,2,1,2),(23,'2018-05-17',NULL,'2018-05-17',80000003,NULL,900,3,1300,1300,NULL,NULL),(24,'2018-05-17',NULL,'2018-05-17',80000004,NULL,900,1,1300,1300,NULL,NULL),(25,'2018-05-17',NULL,'2018-05-17',80000005,NULL,900,2,1300,1300,NULL,NULL),(26,'2018-05-17',NULL,'2018-05-17',80000006,NULL,900,3,1300,1300,NULL,NULL),(27,'2018-05-17','2018-05-17','2018-05-17',80000007,NULL,900,1,1300,1300,NULL,NULL),(28,'2018-05-17',NULL,'2018-05-17',80000008,NULL,900,3,1300,1300,NULL,NULL),(29,'2018-05-17',NULL,'2018-05-17',80000009,NULL,900,3,1300,1300,NULL,NULL);
  /*!40000 ALTER TABLE `STELLPLATZ` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `STETIG_FOERDERER`
  --

  DROP TABLE IF EXISTS `STETIG_FOERDERER`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `STETIG_FOERDERER` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_LAENGE` float DEFAULT NULL,
    `LAGERBEREICH_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_STETIG_FOERDERER_LAGERBEREICH1_idx` (`LAGERBEREICH_P_OID`),
    CONSTRAINT `fk_STETIG_FOERDERER_LAGERBEREICH1` FOREIGN KEY (`LAGERBEREICH_P_OID`) REFERENCES `LAGERBEREICH` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `STETIG_FOERDERER`
  --

  LOCK TABLES `STETIG_FOERDERER` WRITE;
  /*!40000 ALTER TABLE `STETIG_FOERDERER` DISABLE KEYS */;
  INSERT INTO `STETIG_FOERDERER` VALUES (1,NULL,NULL,NULL,4.5,1),(2,NULL,NULL,NULL,4.5,1);
  /*!40000 ALTER TABLE `STETIG_FOERDERER` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `TRANSPORTAUFTRAG`
  --

  DROP TABLE IF EXISTS `TRANSPORTAUFTRAG`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `TRANSPORTAUFTRAG` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_TRANSPORTNUMMER` int(11) DEFAULT NULL,
    `P_QUELLE` varchar(45) DEFAULT NULL,
    `P_ZIEL` varchar(45) DEFAULT NULL,
    `P_STATUS` varchar(45) DEFAULT NULL,
    `LOGISTIKZENTRUM_P_OID` int(11) DEFAULT NULL,
    `FLURFOERDERMITTEL_P_OID` int(11) DEFAULT NULL,
    `STETIG_FOERDERER_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_TRANSPORTAUFTRAG_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID`),
    KEY `fk_TRANSPORTAUFTRAG_FLURFOERDERMITTEL1_idx` (`FLURFOERDERMITTEL_P_OID`),
    KEY `fk_TRANSPORTAUFTRAG_STETIG_FOERDERER1_idx` (`STETIG_FOERDERER_P_OID`),
    CONSTRAINT `fk_TRANSPORTAUFTRAG_FLURFOERDERMITTEL1` FOREIGN KEY (`FLURFOERDERMITTEL_P_OID`) REFERENCES `FLURFOERDERMITTEL` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_TRANSPORTAUFTRAG_LOGISTIKZENTRUM1` FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`) REFERENCES `LOGISTIKZENTRUM` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_TRANSPORTAUFTRAG_STETIG_FOERDERER1` FOREIGN KEY (`STETIG_FOERDERER_P_OID`) REFERENCES `STETIG_FOERDERER` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `TRANSPORTAUFTRAG`
  --

  LOCK TABLES `TRANSPORTAUFTRAG` WRITE;
  /*!40000 ALTER TABLE `TRANSPORTAUFTRAG` DISABLE KEYS */;
  INSERT INTO `TRANSPORTAUFTRAG` VALUES (1,'2018-05-17','2018-05-17','2018-05-17',NULL,'23','21','OFFEN',1,4,NULL),(2,'2018-05-17','2018-05-17','2018-05-17',NULL,'24','22','OFFEN',1,4,NULL),(3,'2018-05-17','2018-05-17','2018-05-17',NULL,'21','26','OFFEN',1,3,NULL),(4,'2018-05-17','2018-05-17','2018-05-17',NULL,'22','27','OFFEN',1,3,NULL);
  /*!40000 ALTER TABLE `TRANSPORTAUFTRAG` ENABLE KEYS */;
  UNLOCK TABLES;

  --
  -- Table structure for table `WARE`
  --

  DROP TABLE IF EXISTS `WARE`;
  /*!40101 SET @saved_cs_client     = @@character_set_client */;
  /*!40101 SET character_set_client = utf8 */;
  CREATE TABLE `WARE` (
    `P_OID` int(11) NOT NULL AUTO_INCREMENT,
    `P_ZEITSTEMPEL` date DEFAULT NULL,
    `P_ANLAGE_DATUM` date DEFAULT NULL,
    `P_LETZTE_AENDERUNG` date DEFAULT NULL,
    `P_MENGE` int(11) DEFAULT NULL,
    `P_EINHEITMENGE` varchar(45) DEFAULT NULL,
    `P_EINHEITVOLUMEN` varchar(45) DEFAULT NULL,
    `P_VOLUMEN` float DEFAULT NULL,
    `P_PACKUNGSGROESSE` float DEFAULT NULL,
    `LOGISTIKZENTRUM_P_OID` int(11) DEFAULT NULL,
    `BESTELLUNG_P_OID` int(11) DEFAULT NULL,
    `LADEHILFSMITTEL_P_OID` int(11) DEFAULT NULL,
    PRIMARY KEY (`P_OID`),
    KEY `fk_WARE_LOGISTIKZENTRUM1_idx` (`LOGISTIKZENTRUM_P_OID`),
    KEY `fk_WARE_BESTELLUNG1_idx` (`BESTELLUNG_P_OID`),
    KEY `fk_WARE_LADEHILFSMITTEL1_idx` (`LADEHILFSMITTEL_P_OID`),
    CONSTRAINT `fk_WARE_BESTELLUNG1` FOREIGN KEY (`BESTELLUNG_P_OID`) REFERENCES `BESTELLUNG` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_WARE_LADEHILFSMITTEL1` FOREIGN KEY (`LADEHILFSMITTEL_P_OID`) REFERENCES `LADEHILFSMITTEL` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_WARE_LOGISTIKZENTRUM1` FOREIGN KEY (`LOGISTIKZENTRUM_P_OID`) REFERENCES `LOGISTIKZENTRUM` (`P_OID`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;
  /*!40101 SET character_set_client = @saved_cs_client */;

  --
  -- Dumping data for table `WARE`
  --

  LOCK TABLES `WARE` WRITE;
  /*!40000 ALTER TABLE `WARE` DISABLE KEYS */;
  INSERT INTO `WARE` VALUES (1,NULL,NULL,NULL,200,'St','ml',500,15,1,1,NULL),(2,NULL,NULL,NULL,200,'St','ml',500,15,1,1,NULL),(3,NULL,NULL,NULL,200,'St','ml',500,15,1,2,NULL),(4,NULL,NULL,NULL,200,'St','ml',500,15,1,2,NULL),(5,NULL,NULL,NULL,200,'St','ml',500,15,1,3,NULL);
  /*!40000 ALTER TABLE `WARE` ENABLE KEYS */;
  UNLOCK TABLES;
  /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

  /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
  /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
  /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
  /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
  /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
  /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
  /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

  -- Dump completed on 2018-05-17 14:06:44

  ";

}

?>
